//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCOMER.VUI.INS.WS_INS_CotizacionEmisionPoliza_Pruebas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_INS_CotizacionEmisionPolizas" +
        "Riesgo")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_INS_CotizacionEmisionPoliza_Pruebas.ICotizacionEmisionPolizas")]
    public interface ICotizacionEmisionPolizas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotizacionEmisionPolizas/CotizacionEmisionPoliza", ReplyAction="http://tempuri.org/ICotizacionEmisionPolizas/CotizacionEmisionPolizaResponse")]
        PROCOMER.VUI.INS.WS_INS_CotizacionEmisionPoliza_Pruebas.Respuesta CotizacionEmisionPoliza(string jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotizacionEmisionPolizas/CotizacionEmisionPoliza", ReplyAction="http://tempuri.org/ICotizacionEmisionPolizas/CotizacionEmisionPolizaResponse")]
        System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_CotizacionEmisionPoliza_Pruebas.Respuesta> CotizacionEmisionPolizaAsync(string jsonData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICotizacionEmisionPolizasChannel : PROCOMER.VUI.INS.WS_INS_CotizacionEmisionPoliza_Pruebas.ICotizacionEmisionPolizas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CotizacionEmisionPolizasClient : System.ServiceModel.ClientBase<PROCOMER.VUI.INS.WS_INS_CotizacionEmisionPoliza_Pruebas.ICotizacionEmisionPolizas>, PROCOMER.VUI.INS.WS_INS_CotizacionEmisionPoliza_Pruebas.ICotizacionEmisionPolizas {
        
        public CotizacionEmisionPolizasClient() {
        }
        
        public CotizacionEmisionPolizasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CotizacionEmisionPolizasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CotizacionEmisionPolizasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CotizacionEmisionPolizasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PROCOMER.VUI.INS.WS_INS_CotizacionEmisionPoliza_Pruebas.Respuesta CotizacionEmisionPoliza(string jsonData) {
            return base.Channel.CotizacionEmisionPoliza(jsonData);
        }
        
        public System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_CotizacionEmisionPoliza_Pruebas.Respuesta> CotizacionEmisionPolizaAsync(string jsonData) {
            return base.Channel.CotizacionEmisionPolizaAsync(jsonData);
        }
    }
}
