//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCOMER.VUI.INS.WS_INS_ConsultaCertificaciones_Pruebas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Param", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_INS_ConsultaCertificacionPol" +
        "izas")]
    [System.SerializableAttribute()]
    public partial class Param : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCertificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroPolizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoProcesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCertificacion {
            get {
                return this.NumeroCertificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCertificacionField, value) != true)) {
                    this.NumeroCertificacionField = value;
                    this.RaisePropertyChanged("NumeroCertificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroPoliza {
            get {
                return this.NumeroPolizaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroPolizaField, value) != true)) {
                    this.NumeroPolizaField = value;
                    this.RaisePropertyChanged("NumeroPoliza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoProceso {
            get {
                return this.TipoProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoProcesoField, value) != true)) {
                    this.TipoProcesoField = value;
                    this.RaisePropertyChanged("TipoProceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_INS_ConsultaCertificacionPol" +
        "izas")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_INS_ConsultaCertificaciones_Pruebas.ICertificacionPolizas")]
    public interface ICertificacionPolizas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificacionPolizas/ConsultaCertificacion", ReplyAction="http://tempuri.org/ICertificacionPolizas/ConsultaCertificacionResponse")]
        PROCOMER.VUI.INS.WS_INS_ConsultaCertificaciones_Pruebas.Respuesta ConsultaCertificacion(PROCOMER.VUI.INS.WS_INS_ConsultaCertificaciones_Pruebas.Param param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificacionPolizas/ConsultaCertificacion", ReplyAction="http://tempuri.org/ICertificacionPolizas/ConsultaCertificacionResponse")]
        System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_ConsultaCertificaciones_Pruebas.Respuesta> ConsultaCertificacionAsync(PROCOMER.VUI.INS.WS_INS_ConsultaCertificaciones_Pruebas.Param param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificacionPolizas/ConsultaCertificacionJson", ReplyAction="http://tempuri.org/ICertificacionPolizas/ConsultaCertificacionJsonResponse")]
        string ConsultaCertificacionJson(string jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificacionPolizas/ConsultaCertificacionJson", ReplyAction="http://tempuri.org/ICertificacionPolizas/ConsultaCertificacionJsonResponse")]
        System.Threading.Tasks.Task<string> ConsultaCertificacionJsonAsync(string jsonData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICertificacionPolizasChannel : PROCOMER.VUI.INS.WS_INS_ConsultaCertificaciones_Pruebas.ICertificacionPolizas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CertificacionPolizasClient : System.ServiceModel.ClientBase<PROCOMER.VUI.INS.WS_INS_ConsultaCertificaciones_Pruebas.ICertificacionPolizas>, PROCOMER.VUI.INS.WS_INS_ConsultaCertificaciones_Pruebas.ICertificacionPolizas {
        
        public CertificacionPolizasClient() {
        }
        
        public CertificacionPolizasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CertificacionPolizasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificacionPolizasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificacionPolizasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PROCOMER.VUI.INS.WS_INS_ConsultaCertificaciones_Pruebas.Respuesta ConsultaCertificacion(PROCOMER.VUI.INS.WS_INS_ConsultaCertificaciones_Pruebas.Param param) {
            return base.Channel.ConsultaCertificacion(param);
        }
        
        public System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_ConsultaCertificaciones_Pruebas.Respuesta> ConsultaCertificacionAsync(PROCOMER.VUI.INS.WS_INS_ConsultaCertificaciones_Pruebas.Param param) {
            return base.Channel.ConsultaCertificacionAsync(param);
        }
        
        public string ConsultaCertificacionJson(string jsonData) {
            return base.Channel.ConsultaCertificacionJson(jsonData);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaCertificacionJsonAsync(string jsonData) {
            return base.Channel.ConsultaCertificacionJsonAsync(jsonData);
        }
    }
}
