//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCOMER.VUI.INS.WS_INS_ConsultaPolizas_Pruebas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Param", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_ConsultaPolizas")]
    [System.SerializableAttribute()]
    public partial class Param : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTipoIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaDesdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroPolizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoProcesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTipoIdentificacion {
            get {
                return this.CodigoTipoIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTipoIdentificacionField, value) != true)) {
                    this.CodigoTipoIdentificacionField = value;
                    this.RaisePropertyChanged("CodigoTipoIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaDesde {
            get {
                return this.FechaDesdeField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaDesdeField, value) != true)) {
                    this.FechaDesdeField = value;
                    this.RaisePropertyChanged("FechaDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionField, value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroPoliza {
            get {
                return this.NumeroPolizaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroPolizaField, value) != true)) {
                    this.NumeroPolizaField = value;
                    this.RaisePropertyChanged("NumeroPoliza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoProceso {
            get {
                return this.TipoProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoProcesoField, value) != true)) {
                    this.TipoProcesoField = value;
                    this.RaisePropertyChanged("TipoProceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_ConsultaPolizas")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_INS_ConsultaPolizas_Pruebas.IConsultaPolizas")]
    public interface IConsultaPolizas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaPolizas/ConsultaPoliza", ReplyAction="http://tempuri.org/IConsultaPolizas/ConsultaPolizaResponse")]
        PROCOMER.VUI.INS.WS_INS_ConsultaPolizas_Pruebas.Respuesta ConsultaPoliza(PROCOMER.VUI.INS.WS_INS_ConsultaPolizas_Pruebas.Param param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaPolizas/ConsultaPoliza", ReplyAction="http://tempuri.org/IConsultaPolizas/ConsultaPolizaResponse")]
        System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_ConsultaPolizas_Pruebas.Respuesta> ConsultaPolizaAsync(PROCOMER.VUI.INS.WS_INS_ConsultaPolizas_Pruebas.Param param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaPolizas/ConsultaPolizajson", ReplyAction="http://tempuri.org/IConsultaPolizas/ConsultaPolizajsonResponse")]
        string ConsultaPolizajson(string jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaPolizas/ConsultaPolizajson", ReplyAction="http://tempuri.org/IConsultaPolizas/ConsultaPolizajsonResponse")]
        System.Threading.Tasks.Task<string> ConsultaPolizajsonAsync(string jsonData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultaPolizasChannel : PROCOMER.VUI.INS.WS_INS_ConsultaPolizas_Pruebas.IConsultaPolizas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaPolizasClient : System.ServiceModel.ClientBase<PROCOMER.VUI.INS.WS_INS_ConsultaPolizas_Pruebas.IConsultaPolizas>, PROCOMER.VUI.INS.WS_INS_ConsultaPolizas_Pruebas.IConsultaPolizas {
        
        public ConsultaPolizasClient() {
        }
        
        public ConsultaPolizasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaPolizasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaPolizasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaPolizasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PROCOMER.VUI.INS.WS_INS_ConsultaPolizas_Pruebas.Respuesta ConsultaPoliza(PROCOMER.VUI.INS.WS_INS_ConsultaPolizas_Pruebas.Param param) {
            return base.Channel.ConsultaPoliza(param);
        }
        
        public System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_ConsultaPolizas_Pruebas.Respuesta> ConsultaPolizaAsync(PROCOMER.VUI.INS.WS_INS_ConsultaPolizas_Pruebas.Param param) {
            return base.Channel.ConsultaPolizaAsync(param);
        }
        
        public string ConsultaPolizajson(string jsonData) {
            return base.Channel.ConsultaPolizajson(jsonData);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaPolizajsonAsync(string jsonData) {
            return base.Channel.ConsultaPolizajsonAsync(jsonData);
        }
    }
}
