//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoIdentificacion", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_INS_Catalogos.Models")]
    [System.SerializableAttribute()]
    public partial class TipoIdentificacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrip {
            get {
                return this.DescripField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripField, value) != true)) {
                    this.DescripField = value;
                    this.RaisePropertyChanged("Descrip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPoliza", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_INS_Catalogos.Models")]
    [System.SerializableAttribute()]
    public partial class TipoPoliza : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrip {
            get {
                return this.DescripField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripField, value) != true)) {
                    this.DescripField = value;
                    this.RaisePropertyChanged("Descrip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormaPago", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_INS_Catalogos.Models")]
    [System.SerializableAttribute()]
    public partial class FormaPago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrip {
            get {
                return this.DescripField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripField, value) != true)) {
                    this.DescripField = value;
                    this.RaisePropertyChanged("Descrip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoPoliza", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_INS_Catalogos")]
    [System.SerializableAttribute()]
    public partial class EstadoPoliza : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrip {
            get {
                return this.DescripField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripField, value) != true)) {
                    this.DescripField = value;
                    this.RaisePropertyChanged("Descrip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ocupacion", Namespace="http://schemas.datacontract.org/2004/07/WCF_PROCOMER_INS_Catalogos")]
    [System.SerializableAttribute()]
    public partial class Ocupacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrip {
            get {
                return this.DescripField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripField, value) != true)) {
                    this.DescripField = value;
                    this.RaisePropertyChanged("Descrip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_INS_Catalogos_Pruebas.ICatalogos")]
    public interface ICatalogos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/TipoIdentificaciones", ReplyAction="http://tempuri.org/ICatalogos/TipoIdentificacionesResponse")]
        PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.TipoIdentificacion[] TipoIdentificaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/TipoIdentificaciones", ReplyAction="http://tempuri.org/ICatalogos/TipoIdentificacionesResponse")]
        System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.TipoIdentificacion[]> TipoIdentificacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/TipoPolizas", ReplyAction="http://tempuri.org/ICatalogos/TipoPolizasResponse")]
        PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.TipoPoliza[] TipoPolizas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/TipoPolizas", ReplyAction="http://tempuri.org/ICatalogos/TipoPolizasResponse")]
        System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.TipoPoliza[]> TipoPolizasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/FormaPagos", ReplyAction="http://tempuri.org/ICatalogos/FormaPagosResponse")]
        PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.FormaPago[] FormaPagos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/FormaPagos", ReplyAction="http://tempuri.org/ICatalogos/FormaPagosResponse")]
        System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.FormaPago[]> FormaPagosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/EstadoPolizas", ReplyAction="http://tempuri.org/ICatalogos/EstadoPolizasResponse")]
        PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.EstadoPoliza[] EstadoPolizas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/EstadoPolizas", ReplyAction="http://tempuri.org/ICatalogos/EstadoPolizasResponse")]
        System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.EstadoPoliza[]> EstadoPolizasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/Ocupaciones", ReplyAction="http://tempuri.org/ICatalogos/OcupacionesResponse")]
        PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.Ocupacion[] Ocupaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/Ocupaciones", ReplyAction="http://tempuri.org/ICatalogos/OcupacionesResponse")]
        System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.Ocupacion[]> OcupacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/TipoIdentificacionesJson", ReplyAction="http://tempuri.org/ICatalogos/TipoIdentificacionesJsonResponse")]
        string TipoIdentificacionesJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/TipoIdentificacionesJson", ReplyAction="http://tempuri.org/ICatalogos/TipoIdentificacionesJsonResponse")]
        System.Threading.Tasks.Task<string> TipoIdentificacionesJsonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/TipoPolizasJson", ReplyAction="http://tempuri.org/ICatalogos/TipoPolizasJsonResponse")]
        string TipoPolizasJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/TipoPolizasJson", ReplyAction="http://tempuri.org/ICatalogos/TipoPolizasJsonResponse")]
        System.Threading.Tasks.Task<string> TipoPolizasJsonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/FormaPagosJson", ReplyAction="http://tempuri.org/ICatalogos/FormaPagosJsonResponse")]
        string FormaPagosJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/FormaPagosJson", ReplyAction="http://tempuri.org/ICatalogos/FormaPagosJsonResponse")]
        System.Threading.Tasks.Task<string> FormaPagosJsonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/EstadoPolizasJson", ReplyAction="http://tempuri.org/ICatalogos/EstadoPolizasJsonResponse")]
        string EstadoPolizasJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/EstadoPolizasJson", ReplyAction="http://tempuri.org/ICatalogos/EstadoPolizasJsonResponse")]
        System.Threading.Tasks.Task<string> EstadoPolizasJsonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/OcupacionesJson", ReplyAction="http://tempuri.org/ICatalogos/OcupacionesJsonResponse")]
        string OcupacionesJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogos/OcupacionesJson", ReplyAction="http://tempuri.org/ICatalogos/OcupacionesJsonResponse")]
        System.Threading.Tasks.Task<string> OcupacionesJsonAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogosChannel : PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.ICatalogos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogosClient : System.ServiceModel.ClientBase<PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.ICatalogos>, PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.ICatalogos {
        
        public CatalogosClient() {
        }
        
        public CatalogosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.TipoIdentificacion[] TipoIdentificaciones() {
            return base.Channel.TipoIdentificaciones();
        }
        
        public System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.TipoIdentificacion[]> TipoIdentificacionesAsync() {
            return base.Channel.TipoIdentificacionesAsync();
        }
        
        public PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.TipoPoliza[] TipoPolizas() {
            return base.Channel.TipoPolizas();
        }
        
        public System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.TipoPoliza[]> TipoPolizasAsync() {
            return base.Channel.TipoPolizasAsync();
        }
        
        public PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.FormaPago[] FormaPagos() {
            return base.Channel.FormaPagos();
        }
        
        public System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.FormaPago[]> FormaPagosAsync() {
            return base.Channel.FormaPagosAsync();
        }
        
        public PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.EstadoPoliza[] EstadoPolizas() {
            return base.Channel.EstadoPolizas();
        }
        
        public System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.EstadoPoliza[]> EstadoPolizasAsync() {
            return base.Channel.EstadoPolizasAsync();
        }
        
        public PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.Ocupacion[] Ocupaciones() {
            return base.Channel.Ocupaciones();
        }
        
        public System.Threading.Tasks.Task<PROCOMER.VUI.INS.WS_INS_Catalogos_Pruebas.Ocupacion[]> OcupacionesAsync() {
            return base.Channel.OcupacionesAsync();
        }
        
        public string TipoIdentificacionesJson() {
            return base.Channel.TipoIdentificacionesJson();
        }
        
        public System.Threading.Tasks.Task<string> TipoIdentificacionesJsonAsync() {
            return base.Channel.TipoIdentificacionesJsonAsync();
        }
        
        public string TipoPolizasJson() {
            return base.Channel.TipoPolizasJson();
        }
        
        public System.Threading.Tasks.Task<string> TipoPolizasJsonAsync() {
            return base.Channel.TipoPolizasJsonAsync();
        }
        
        public string FormaPagosJson() {
            return base.Channel.FormaPagosJson();
        }
        
        public System.Threading.Tasks.Task<string> FormaPagosJsonAsync() {
            return base.Channel.FormaPagosJsonAsync();
        }
        
        public string EstadoPolizasJson() {
            return base.Channel.EstadoPolizasJson();
        }
        
        public System.Threading.Tasks.Task<string> EstadoPolizasJsonAsync() {
            return base.Channel.EstadoPolizasJsonAsync();
        }
        
        public string OcupacionesJson() {
            return base.Channel.OcupacionesJson();
        }
        
        public System.Threading.Tasks.Task<string> OcupacionesJsonAsync() {
            return base.Channel.OcupacionesJsonAsync();
        }
    }
}
